resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
      instances:
        products:
          base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
      instances:
        products:
          base-config: default

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server-service
  cloud:
    gateway:
      routes:
      - id: productsModule
        uri: lb://SERVICE-PRODUCT
        predicates:
          - Path=/products/**
        filters:
          - name: CircuitBreaker
            args:
              name: products
              statusCodes: 500
              fallbackUri: forward:/items/view3/1/quantity/45
          - ExampleCookie=Hello my custom message, Alexlondon07, user
      - id: itemsModule
        uri: lb://ITEMS-SERVICE
        predicates:
          - Path=/items/**
        filters:
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - AddRequestParameter=name, Alexlondon07
      - id: userModule
        uri: lb://USERS-SERVICE
        predicates:
          - Path=/users/**
      - id: oauthModule
        uri: lb://OAUTH-SERVICE
        predicates:
          - Path=/security/**
        filters:
          - RemoveRequestHeader=Cookie

