server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server-service
  cloud:
    gateway:
      routes:
      - id: productsModule
        uri: lb://SERVICE-PRODUCT
        predicates:
          - Path=/products/**
      - id: itemsModule
        uri: lb://ITEMS-SERVICE
        predicates:
          - Path=/items/**