server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server-service
  cloud:
    gateway:
      routes:
      - id: productsModule
        uri: lb://SERVICE-PRODUCT
        predicates:
          - Path=/products/**
        filters:
          - ExampleCookie=Hello my custom message, Alexlondon07, user
      - id: itemsModule
        uri: lb://ITEMS-SERVICE
        predicates:
          - Path=/items/**
        filters:
          - AddRequestHeader=token-request, 123456
          - AddResponseHeader=token-response, 12345678
          - AddRequestParameter=name, Alexlondon07